api_consumption/urls.py
from django.contrib import admin

from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('project.urls')),
  
    
]


urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from .views import *
from .import views 




app_name ="project"

urlpatterns = [
  
    path('' ,views.home,name='home'),
    path('check/' ,views.json_dumps,name='check'),
     path('search/' ,views.search,name='search'),
      path('contact/' ,views.contactMe,name='contact'),
   
]    

project/models.py
from django.db import models

from cloudinary.models import CloudinaryField
# Create your models here.

class Search(models.Model):
    title = models.CharField(max_length=500)
    search = models.CharField(max_length = 100)
    date_searched = models.DateTimeField(auto_now_add=True, null=True)
    owner_id = models.CharField(max_length=100)
    tags = models.CharField(max_length=500)
    #owner_id = models.CharField(max_length=100)
    profile = CloudinaryField(blank=True,null=True)
    owner_name = models.CharField(max_length=200)
    owner_link = models.CharField(max_length=1000)
    is_answer = models.BooleanField(default=False)
    view_count = models.CharField(max_length=200)
    question_id = models.CharField(max_length=100)
  
    
    stflow_link = models.CharField(max_length=100)
    last_activity_date =models.CharField(max_length=100)
    creation_date = models.CharField(max_length=100)


    def __str__(self):
        return '{}'.format(self.search)


    class Meta:
        verbose_name_plural ='Searches'






class ContactUs(models.Model):

   name = models.CharField(max_length=100) 
   email = models.EmailField(unique = False) 
   phone = models.CharField(max_length=20) 
   selected_properties =models.CharField(max_length=100) 

   message = models.TextField(max_length=200)


   class Meta:
      verbose_name_plural = "ContactMe"

   def __str__(self):
      return self.name 

 

project/views.py
import re
from django.shortcuts import render,redirect ,get_object_or_404, resolve_url
from django.contrib import auth, messages
import json

import requests
from django.utils import timezone


from django.http import HttpResponse,JsonResponse, request
from django.forms import inlineformset_factory
from django.views.generic.base import TemplateView

from django.contrib.auth.mixins import LoginRequiredMixin ,UserPassesTestMixin

from django.views.generic import (
    ListView ,DetailView, CreateView, UpdateView ,DeleteView
    )
from requests.compat import quote_plus





from django.db.models import Q 

from django.core.mail import send_mail
from .models import *
from django.conf import settings
from .forms import *

answer ='https://api.stackexchange.com/2.3/answers?order=desc&sort=activity&site=stackoverflow'


BASE_NUEL_URL  = requests.get('https://api.stackexchange.com/2.3/questions?order=desc&sort=activity&site=stackoverflow')
  




def home(request):
    rs = requests.get('https://api.stackexchange.com/2.3/questions?order=desc&sort=activity&site=stackoverflow')
    json_data = rs.json()

    pack_str = json.dumps(json_data['items'],indent=2)
    json_data =json_data['items']
    num =len(pack_str)

    context={
        'json_data':json_data,
        'num':num,
        'pack_str':pack_str
    }

    return render(request, 'home.html',context)




def json_dumps(request):

    response = requests.get(BASE_NUEL_URL)
    resp = response.json()
    for data in response.json()['items']:

        title=data['title']
        #link=data['links']
        date=data['creation_date']
       # name=data['displayed_name']
            

        
    #data=resp.items
    
   
    #item =response.items.dict_items
        context={
        #'link':link,
        'date':date,
        #'name':name,
        'title':title,
        #'item':item,
        'data':data,
        'resp':resp,
        'response':response,
        
    }

   #for data in response.json():

      # print(data)
      # context = {
       # 'ques':data,
       # }
    return render(request, 'data.html',context)





def search(request):
    json_data = BASE_NUEL_URL
    query = request.GET.get('search')
    json_data = json_data.json()

    json_data =json_data['items']
   
    context ={'json_data':json_data,'query':query}
    return render(request,'search.html',context)   
         
    


def sea(request):
    json_data = BASE_NUEL_URL.text
    query = request.GET.get('search')
    json_obj = json.loads(json_data)
   
    if query in json_obj.items():

        output_dict = [x for x in json_obj if x['tags'] == query]
        output_json = json.dumps(output_dict)
    

        data =json_data['items']
        for issues in data:
            context ={'issues':issues}
   
        info=issues
        for item in issues['tags']:
            if query in item:
                print(query)

    return render(request,'search.html') 







def check(request):
    json_data = requests.get(BASE_NUEL_URL)
    query = request.GET.get('search')

    for data in json_data.json()['items']:
        if data['answer_count'] ==0:
            title =data['title']
            link = data['link']
            context ={
                'title':title,
                'link':link
            }
            return render(request,'search.html',context)

        else:
            pass
        return render(request,'search.html')



    



def contactMe(request):
  

    if request.method =='POST':
        message_name = request.POST['message-name']
        message_phone = request.POST.get("message-phone" ,False)
        message_email = request.POST['message-email']
        message  = request.POST['message']
       # products_name =request.POST['property']
        products = request.POST.getlist('property')




        # seend a mail
        # the order in which  to  pass arugument in the parameters is important
        send_mail(
            message_name , # email subject
            #message_phone, #phone no
            message_email , # from email 
            message ,      # main message
            #products, # items

            [settings.EMAIL_HOST_USER], # recipient, to email
        fail_silently=False)
        
        
        #contacts = ContactUs(name=message_name ,phone=message_phone ,email=message_email ,message=message)
        contacts = ContactUs()
        contacts.name =message_name
        contacts.phone = message_phone
        contacts.email = message_email
        contacts.selected_properties = products
        contacts.message = message
        contacts.save()


        return render(request ,'email.html',{'message_name' :message_name}) 

    else:
        return render(request ,'contact.html') 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Json Consumption {% endblock %}</title>
</head>
<body>
    

    

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'styles/css.css' %}">
   


   <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/" style="color:green">Nuel<Span style="color: hsl(0, 87%, 43%);">University</Span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'project:contact' %}">Contact Me</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Python</a>
          </li>
         
        </ul>
        <form class="d-flex" method="GET" action="{% url 'project:search' %}">
          <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>


{% block content %}
{% endblock %}





<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ContactUs{% endblock %}
{% block content %}
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />-->




<style>
 
.contact-info{
        height: 200px;
       
  font-family: "Roboto", sans-serif;
  margin-left: 5px;

  background-color: #cccccc; 

 
}
.card-info{
   
    color: #fff;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
}
.card-info h1{
    font-size:20px;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    font-weight: 800;
    margin-top: 30px;
    text-align: center;
  
}
.card-phone{
   
   color: #fff;
   font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
}
.card-phone h2{
    text-align: center;
    color: green;
    font-size: 18px;
    font-weight: 500;
    text-transform: capitalize;
    font-family: "Roboto", sans-serif;
    
}
.card-phone p{
    text-align: center;
    color: #fff;
    font-size: 18px;
    line-height: 15px;
    font-weight: 600;
    margin-top: 20px;

}
.card-message .input-data{
    background-color: #fff;
   
    border-radius: 0%;
    width: 80%;
    margin-left: auto;
    margin-right: auto;
     
}


.card-message{
   
    background-image: linear-gradient(135deg,rgb(74,234,220) 0%,#d5dfdb 100%);

}

.textarea{
    margin-top: 30px;
}

#exampleFormControlTextarea1{
    width: 80%;
    margin-left: auto;
    margin-right: auto;
}


.contactMe{
    margin-top: 30px;
}
.contact-details{
    box-shadow: 0 4px 8px 0 #000;
    height: 200px; 
}
.mb-4 h1{
    text-align: center;
    font-size: 20px;
}
.center{
    margin: 20px;
}
/*overflow-wrap: break-word;*/
</style>



<div class="container contactMe" >
    <div class="row">
        <div class="col-md-6">
          
           <div class="contact-info ">
              <div class="contact-details team-body-side animate__animated animate__backInLeft">
                <div class="card-info ">
                    <h1>Contact Information</h1>
                </div>
                <div class="card-phone">
                    <h2>phone:</h2>
                    <p>+2348079385255 </p>
                   
                </div>
                <div class="card-phone">
                 <h2>email:</h2>
                 <p>nuel4xelence@gmail.com</p>
              
               
             </div>
          
         
              </div>
           </div>
        </div>

        <div class="col-md-6 message-us">
            <div class="card-message">

              

                <form action="{% url 'project:contact' %}" method="post" class="team-body-side animate__animated animate__backInRight">
                    {% csrf_token %}
                    <div class="mb-4 mess" style="padding-top: 30px; color: rgb(254,45,45);">
                        <h1>Message us:</h1>
                                   
                      </div>
                    <div class="mb-3">
                  
                        <input class="form-control input-data" type="text" name="message-name" id="exampleFormControlInput1"  placeholder="Name" aria-label="default input example">
                    
                      </div>
                      <div class="mb-3">
 
                        <input class="form-control input-data" id="" type="number" name="message-phone" placeholder=" phone number">
                      </div>

                    <div class="mb-3">
                 
                      <input type="email" class="form-control input-data" name="message-email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder=" Email address">
                                 
                    </div>
                    
                    <div class="mb-3 textarea">

                        <textarea class="form-control" name="message" id="exampleFormControlTextarea1" rows="3" placeholder="please type your message here"></textarea>
                      </div>


                    <button type="submit" class="btn btn-danger center">Submit</button>
                    </form>
            </div>
        </div>
    </div>
</div>







{% endblock %}

templates/data.html
<a href="{% url 'project:check' %}">check info</a>
<br>
<br>
{{lk}}
{{title}}
{{link}}
{{date}}
{{name}}

<h2 style="color: yellow;">item:json</h2>
{{item}}

<h2 style="color: black;">data: items with json</h2>
{{data}}

<h2 style="color:red;">json product</h2>
{{resp}}





<h1 style="color:green;">raw data</h1>
{{response}}

templates/email.html
{% extends 'first.html' %}
 {% load static %}
 
 {% block title %}Email Confirmation{% endblock %}
{% block content %}


<style>
     .want_to_buy{
        display: none;
    }
    .display{
        display: none;
    }
    .property-search{
        display: none;
    }
    .featured{
        display: none;
    }

    .email-received{
        margin-bottom: 120px;
        margin-top: 100px;
        font-size: 18px;
        text-align: center;
        color: #cf2e2e;
    }
    .email-received p{
        text-align: center;
        font-size: 14px;
        color: #333;
    }
  
  </style>
<center class="email-received">
    <h1> Thank you , {{ message_name }}</h1>
    <p>Email recieved,we will contact you soon</p>
</center>



{% include 'footer.html' %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Questions{% endblock %}
{% block content %}






  

<div class="container" style=" margin-top: 30px; margin-bottom: 30px;"  >
    <div class="card" style="background:hsl(0, 87%, 43%);" >
        <h1 class="search-result" style="color:#fff; text-align:center; width: auto;">API Consumption From stackoverflow.com</h1>
    </div>
</div>

<div class="search-section">
    
    <h1 class="search-result">Questions asked in stackoverflow.com</h1>

    {% for data in json_data %}
<div class="flex-container" style="margin-top:30px;">
    
   
  <div>
  

    <div class="property-flex">
        
        <a href="{{data.link}}">
        <div class="card-image ">
 
            <img class="img-with-animation skip-lazy animated-in" data-delay="0" height="50" width="130" data-animation="fade-in" src="{{data.owner.profile_image}}" alt="/static/images/no_img.png">
 
        </div>
        </a>
    </div>
  </div>
  <div>
      <div class="property-information">
         <a href="{{data.link}}">
            <div class="property-address">
                <h2>Post By: {{ data.owner.display_name}} </h2>
            </div>
         </a><br>
          <div class="property-information">
              <h3>Question:<span> {{data.title}}</span></h3>
              <h3>Question  Related to: {{data.tags}}</h3>
              <h3>Question Id: {{data.question_id}}</h3>
              <h3>How Mnay Answers Given: {{data.answer_count}}</h3>
              <h3>Seen By :{{data.view_count}} &nbsp; People</h3>
              <h3>Reputation:{{data.owner.reputation}}</h3>
              <h3>Date Posted:{{data.creation_date}}</h3>
              <h3>Last Active Date:{{data.last_activity_date}}</h3>
          </div>
      </div>
  </div>
  <!--<div class="property-information">
      <h3 class="right">Answered : {{data.is_answered}}</h3>
      <h3 class="right">Listing ID50044316PBMLS-RETS</h3>
  </div>  -->
  <!--<div class="property-information">
    <h3 class="center">Registered User: {{data.owner.user_type}}</h3>
    
</div> --> 
</div>

<div class="contar">
<div class="btn-groupy " role="group" aria-label="Basic mixed styles example">
   
    <!--<a href="" type="button" class="btn btnb btn-danger">View pictures</a>
    <a href="" type="button" class="btn btnb btn-warning">Visual Tour</a>
  
    <a href="" type="button" class="btn btnb btn-success" >Add To Your Wishlist</a>-->
    <a href="{{data.link}}"  >Link to original question in stackoverflow</a>
  </div>
</div>

</div>


{% endfor %}












<!--{{num}} <br>
{% for d in json_data %}
 <h3 style="color:green">{{d.tags}}</h3>
 <h3 style="color:black">{{d.owner}}</h3><br>
<div class="container" style="background: blue;">
    <h3 style="color:black">{{d.owner.account_id}}</h3>
    <h3 style="color:black">{{d.owner.reputation}}</h3>
    <h3 style="color:black">{{d.owner.user_id}}</h3>
    <h3 style="color:black">{{d.owner.user_type}}</h3>.
    <h3 style="color:black">{{d.owner.profile_image}}</h3>.
    <h3 style="color:black">{{d.owner.display_name}}</h3>.
    <h3 style="color:black">{{d.owner.link}}</h3>
</div>
 <h3 style="color:red">{{d.is_answered}}</h3>
 <h3 style="color:red">{{d.is_answered}}</h3>.
 <h3>{{d.view_count}}</h3>.
 <h3>{{d.answer_count}}</h3>.
 <h3>{{d.score}}</h3>
 <h3>{{d.last_activity_date}}</h3>
 <h3>{{d.creation_date}}</h3>
 <h3>{{d.question_id}}</h3>.
 <h3> Licence:{{d.content_licence}}</h3>
 <h3>{{d.link}}</h3>
 <h3>{{d.title}}</h3>.
 <h3>{{d.answer_count}}</h3>
{% endfor %}
<h2 style="color:blue">{{json_data}}</h2>

{% for info in pack_str %}
 <h3> onenum {{info}}</h3>
{% endfor %}


<h3 style="color:red;">end here</h3>
{{pack_str}}-->


{% endblock %}

templates/not_found.html
<h3>Nothing found</h3>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Questions{% endblock %}
{% block content %}

  

<div class="container" style=" margin-top: 30px; margin-bottom: 30px;"  >
    <div class="card" style="background:hsl(0, 87%, 43%);" >
        <h1 class="search-result" style="color:#fff; text-align:center; width: auto;">API Consumption From stackoverflow.com</h1>
    </div>
</div>

<div class="search-section">
    
    <h1 class="search-result">{{query}} questions on stackoverflow.com</h1>

    {% for data in json_data %}
    {% if query in  data.tags %}
<div class="flex-container" style="margin-top:30px;">
    
   
  <div>
  

    <div class="property-flex">
        
        <a href="{{data.link}}">
        <div class="card-image ">
 
            <img class="img-with-animation skip-lazy animated-in" data-delay="0" height="50" width="130" data-animation="fade-in" src="{{data.owner.profile_image}}" alt="/static/images/no_img.png">
 
        </div>
        </a>
    </div>
  </div>
  <div>
      <div class="property-information">
         <a href="{{data.link}}">
            <div class="property-address">
                <h2>Post By: {{ data.owner.display_name}} </h2>
            </div>
         </a><br>
          <div class="property-information">
              <h3>Question:<span> {{data.title}}</span></h3>
              <h3>Question  Related to: {{data.tags}}</h3>
              <h3>Question Id: {{data.question_id}}</h3>
              <h3>How Mnay Answers Given: {{data.answer_count}}</h3>
              <h3>Seen By :{{data.view_count}} &nbsp; People</h3>
              <h3>Reputation:{{data.owner.reputation}}</h3>
              <h3>Date Posted:{{data.creation_date}}</h3>
              <h3>Last Active Date:{{data.last_activity_date}}</h3>
          </div>
      </div>
  </div>
  <!--<div class="property-information">
      <h3 class="right">Answered : {{data.is_answered}}</h3>
      <h3 class="right">Listing ID50044316PBMLS-RETS</h3>
  </div>  -->
  <!--<div class="property-information">
    <h3 class="center">Registered User: {{data.owner.user_type}}</h3>
    
</div> --> 
</div>

<div class="contar">
<div class="btn-groupy " role="group" aria-label="Basic mixed styles example">
   
    <!--<a href="" type="button" class="btn btnb btn-danger">View pictures</a>
    <a href="" type="button" class="btn btnb btn-warning">Visual Tour</a>
  
    <a href="" type="button" class="btn btnb btn-success" >Add To Your Wishlist</a>-->
    <a href="{{data.link}}"  >Link to original question in stackoverflow</a>
  </div>
</div>

</div>

 
{% else %}
<h1> </h1>
{% endif %}

{% endfor %}

{% if not query %}
<h3>Nothing found</h3>
{% endif %}


{% endblock %}